---
- name: Playbook para instalar cerbot
  hosts: balanceador
  become: yes


  tasks:

#  ansible-galaxy collection install community.general

# Este paso hay que tener cuidado porque por defecto si lo ejecuto me dar치 fallo
  - name: Desinstalaci칩n de instalaci칩n previa de Certbot
    ansible.builtin.apt:
      name: certbot
      tate: absent

  - name: Instalaci칩n de cerbot mediante snap
    community.general.snap:
      name: certbot
      classic: true
      state: present

  - name: Descarga el certificado 
    ansible.builtin.command: certbot --apache -m {{PS_EMAIL}}  --agree-tos --no-eff-email -d {{DOMAIN}}
    register: my_output
    changed_when: my_output.rc !=0

  - name: Reinicamos apache2
    service: 
      name: apache2
      state: restarted